### ISSUE TITLE
Add custom subreddits?

### ISSUE THREAD

**Issue by Nicole-Evermore** [ByzantineFailure/BPM-for-Discord#101]
Is there any way to add custom subreddits to the draw list for ponymotes? Or is that slated for a later build?

**Comment by ByzantineFailure** [comment]
This was investigated a while ago.  Via issue #19, this is not possible due to Reddit limiting what places can request CSS sheets from them.  Unfortunately this is a feature that is not possible in Discord.  Sorry! :(
