### ISSUE TITLE
Animated Ponymotes do not Animate

### ISSUE THREAD

**Issue by irreama** [ByzantineFailure/BPM-for-Discord#15]
When adding an animated ponymote, such as sonatatrotting it will display, but not animate.

**Comment by Rhiven** [comment]
A few more sample animated emotes: avinyldance, dancershy, gummydance

**Comment by ByzantineFailure** [comment]
Issue part of MVP, priority.

**Comment by ByzantineFailure** [comment]
Fixed as of 3c5a951a52af25bb149ec65843c08565547d7280

Looks like there was a chrome-specific fix for animote CSS inclusion -- because Electron is really just a version of chromium, it needs to apply most of the chrome-specific fixes for CSS and JS (but not extension code).
