### ISSUE TITLE
Install fails with multiple discord versions

### ISSUE THREAD

**Issue by Rhiven** [ByzantineFailure/BPM-for-Discord#16]
Currently the index.js installer grabs the first app-\* directory in %LOCALAPPDATA%/Discord and attempts to use that directory. However Discord leaves old version directories there which causes the install to fail either when it tries to backup the app.asar file (which didn't exist in the first directory I had) or when it adds the BPM file(s) to the wrong version directory. In the latter case the install appears to complete successfully but emotes fail to render.

Instead of taking the first item in the list of directories it would probably be better to take the app-\* directory with the highest version number and use that.

**Comment by ByzantineFailure** [comment]
Should be fixed as of 8fe884a20dec78131de5c5eaf92e21b40322f197
