### ISSUE TITLE
Custom Subreddit CSS

### ISSUE THREAD

**Issue by ByzantineFailure** [ByzantineFailure/BPM-for-Discord#19]
The last thing from Core BPM that we need to integrate.

**Comment by MapleHund** [comment]
So many good emotes I can't use. Please add this.

**Comment by ByzantineFailure** [comment]
This is next up for me when I get some time -- that said, I have some pretty intense stuff going on for the next few weeks outside of coding, etc.  This issue is now the top-prio non-critical issue.

**Comment by ByzantineFailure** [comment]
Initial UI work completed in commit f961dff803fd791770fa87a9409ff1d561e02b70, present on branch custom-css.

It looks like we might get into some cross-origin trouble with the way this stuff is working right now, but I have yet to dig into that.  For now I think I'm gonna leave this.

Additionally, for some reason Discord resets itself whenever a subreddit is added and does not persist the changes through shutdown.  Weird, but still will look into this.

**Comment by ByzantineFailure** [comment]
Failed when testing in Discord.  Moved to browser console and got similar error:

```
XMLHttpRequest cannot load https://www.reddit.com/r/mylittlepony/stylesheet.css. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://developer.mozilla.org' is therefore not allowed access.
```

This occurs for all stylesheets -- reddit doesn't like it when you try and include CSS from their CDN on your site (I wouldn't either if I were them).  The solution would be to manually request this on the backend then load and bundle the CSS in when Discord is started, but that is rather _against_ the spirit of the feature and also far more work than I'd like to do.

Unfortunately unless I can convince someone at reddit to open up `discordapp.com` as a valid origin on an `Access-Control-Allow-Origin` header (or for them to relax their `x-frame-options` header from `SAMEORIGN`), this feature is not going to be possible.  Closing for now.
