### ISSUE TITLE
Disable Emote in Usernames

### ISSUE THREAD

**Issue by tscs37** [ByzantineFailure/BPM-for-Discord#32]
Emotes in usernames are incorrectly replaced.

I suggest the Emote Script should only replace the actual text messages, channel and server descriptions, nothing else.

edit: included online list

**Comment by ByzantineFailure** [comment]
I agree that this can be disruptive, but given that this issue has cropped up at all it looks like some users actually consider this a feature and not a bug.

The best solution here is to add a setting to disable this behavior.

This is more evidence that it may be a good idea to have some discord-specific settings and I'll probably look in to that when I get some free time again.

**Comment by ByzantineFailure** [comment]
This has been added via 3806a1416d02d25798814295153755649c1f20b7 and d1c7bdedfe4899de7e003f05a16ac657ef216fca

It should go out with the next release (probably a week or two, depends when Typhos updates BPM next.  I'm trying to keep my release cycle in sync with his).

**Comment by ByzantineFailure** [comment]
Also committed d5ffa42dfd55d8863fa323a8e7d13c6406531dad

Since the voice users list doesn't _actually_ have class names for each user I had to get a bit... creative to get that to go away.
