### ISSUE TITLE
Create Installer for Mac PTB Client

### ISSUE THREAD

**Issue by ByzantineFailure** [ByzantineFailure/BPM-for-Discord#34]
I ain't got a mac handy so if anyone out there feels like tackling this one or at least pointing me to where the `app.asar` file for the mac PTB client is I'd be much obliged.

**Comment by Shugabuga** [comment]
The `app.asar` file is located at `/Applications/Discord PTB.app/Contents/Resources/app.asar`.

**Comment by ByzantineFailure** [comment]
@Shugabuga Thanks a bunch -- I'll quick make a PTB installer `.command` and make the requisite modification to the node scripts.  Should have this pushed out next update (should be by Saturday night at the latest?)

**Comment by Shugabuga** [comment]
Since the new update has the PTB installer and it works, you may want to close this.

**Comment by ByzantineFailure** [comment]
Doh, thank you.
