### ISSUE TITLE
Cannot re-enable emotes after disabling the

### ISSUE THREAD

**Issue by bloons3** [ByzantineFailure/BPM-for-Discord#35]
If you disable BPM from the options panel
(the emotes)
You cannot open the panel to re-enable BPM
Reinstalling discord + bpm fixes this

**Comment by ByzantineFailure** [comment]
I have been unable to repro this myself.  Untagging as Critical and waiting for another report.

**Comment by bloons3** [comment]
Cannot reproduce

**Comment by ByzantineFailure** [comment]
Closing issue.
