### ISSUE TITLE
Discord Release Folder Structure

### ISSUE THREAD

**Issue by bloons3** [ByzantineFailure/BPM-for-Discord#36]
The current release of BPM for DIscord is a 7zip archive packed with loose files.

If it isn't troubling, would it be possible to have the archive packed with a folder that contains the loose files? This would make it easier to drag to desktop and delete, rather than having to create a new folder.

**Comment by ByzantineFailure** [comment]
Yep!  Few changes to the Makefile and off we go ^_^

**Comment by ByzantineFailure** [comment]
Fixed via 9aef11bf9fe0e74c6035042c9d7f866014f16ee1
