### ISSUE TITLE
Failure to clear screen of certain elements

### ISSUE THREAD

**Issue by bloons3** [ByzantineFailure/BPM-for-Discord#39]
https://cdn.discordapp.com/attachments/115197908986494983/148653089778302977/unknown.png

https://cdn.discordapp.com/attachments/115197908986494983/148653120509968385/unknown.png

Reproduce by searching '+nonpony +nonpony' , and make sure 'USER WAS BANNED BY THIS POST' red text element is on the screen.

When the BPM box is closed, red text will persist.

Text appears over images as well.
https://cdn.discordapp.com/attachments/115197908986494983/148680912622714882/unknown.png

**Comment by bloons3** [comment]
Clicking the leftover text will add the `[](/ban)` tag to the chat box.

**Comment by ByzantineFailure** [comment]
Looking into this some time tonight -- I expect this is an issue with the emote itself and I'll probably have to poke Typhos about it but before I do that I want to make sure it's not some problem in my code.

**Comment by ByzantineFailure** [comment]
This issue repros in browser.  Will look into this starting in the searchbox code.

**Comment by ByzantineFailure** [comment]
As an FYI, I am still aware of this issue -- it's some _really_ weird CSS interaction with how the emote itself is displayed.  I'll probably flag this to Typhos and see if he has any way of handling it.

**Comment by ByzantineFailure** [comment]
Closing this bug here given that it's a mainline issue.  Please re-file it there.
