### ISSUE TITLE
Add ability to load arbitrary CSS to alter the look

### ISSUE THREAD

**Issue by bigfim** [ByzantineFailure/BPM-for-Discord#41]

**Comment by ByzantineFailure** [comment]
@bigfim I think the way I expect to implement this is by allowing custom JS to be run from a `custom` folder inside of the `%APPDATA%/discord/bpm` directory.

You can load arbitrary CSS here by manually loading and attaching it to the document.  This does, unfortunately, mean you have to hardcode your CSS into the JS (or you can use something like `webpack` to do all this unpleasantness for you), but this seems to be the most extensible way to do it.

**Comment by ByzantineFailure** [comment]
Functionality added via b56d83f88554e141d876e562506650a1450e838f
