### ISSUE TITLE
Mac installer fails when the directory of the installer has a space in it

### ISSUE THREAD

**Issue by pixelyunicorn** [ByzantineFailure/BPM-for-Discord#47]
Downloading the latest release then extracting it to a path containing a space yields some interesting results. First, a binary file gets outputted in the terminal.

![image](https://cloud.githubusercontent.com/assets/607807/14448560/c0427d56-0037-11e6-85c5-d194b636bd97.png)

Then, the install fails.

The full path of the installer is "/Users/Bro/Downloads/discord poop", however it shows up only as "/Users/Bro/Downloads/discord" in the terminal.

![image](https://cloud.githubusercontent.com/assets/607807/14448569/d759d5c0-0037-11e6-85e1-e499fe4410f6.png)

**Comment by ByzantineFailure** [comment]
Well shit.  This is what I get for not actually owning a Mac.  Money on this affecting the new Linux installer as well.

I'll work on getting the escaping actually done _right_ on the Mac version ASAP.  Typhos just pushed out a new version of BPM, so I'll get this fix in on the update for that version.

**Comment by ByzantineFailure** [comment]
Got a hold of a mac.  Wow, that did some _really_ weird shit to my shell when I ran it.

Fixed via adding some quotes around anywhere I reference `$DIR` in the command script.  Except where it's used to execute Node.  That would be dumb.

Commit:  de37aa53c10fdfb8b92752eef791e75bab976b63

**Comment by ByzantineFailure** [comment]
Also, just noting this here for shits and giggles, it changed the character set and codepage for that shell instance.  Ain't that a hoot.

**Comment by 00dani** [comment]
Why would it be "dumb" to quote `$DIR` in `$DIR/node`? Bash's parameter expansion works the same way for the command as for its arguments - if there's a space in the value of `DIR` then it won't be able to find the Node binary. For instance:

``` shellsession
$ mkdir /usr/local/Homebrew/'Dir With Spaces'
$ DIR='/usr/local/Homebrew/Dir With Spaces/../../bin'
$ "$DIR"/node --version
v7.0.0
$ $DIR/node --version
bash: /usr/local/Homebrew/Dir: No such file or directory
```

So, yeah, shouldn't it be quoting `$DIR` in that spot too?

**Comment by ByzantineFailure** [comment]
I'm all cool with opening a PR that works here -- I don't reliably have a mac to test on and am still somewhat fuzzy on the details of single vs double quotes in bash scripts :)

If you've got a better-coded version up and cooking on your machine I'll definitely accept the PR!

**Comment by 00dani** [comment]
Hah, yes, shell quoting basically has Bad Defaults. :wink:

The _only_ time a parameter `$x` in a shell script shouldn't be quoted is when the parameter is supposed to produce multiple arguments:

``` bash
GIT_ARGS="commit -a -m 'cool stuff'"
git $GIT_ARGS # works
git "$GIT_ARGS" # 'commit -a -m 'cool stuff'' is not a git command
```

In (almost?) all other cases, a parameter should be quoted with double quotes, `"$x"`. This prevents the shell from splitting it into multiple words, so if it's a path with spaces it'll stick together and work. Finally: there's no parameter expansion in single quotes anyway, so `'$x'` for example will literally produce the string `$x`.

Splitting by default was a necessary feature in older shells, like the original Bourne shell, which only supported string variables. If you're using a newer shell like Bash, then you can just use an array instead, which looks like this:

``` bash
GIT_ARGS=(commit -a -m 'cool stuff')
git "${GIT_ARGS[@]}" # works
```

Or you can use Zsh, which _doesn't_ split by default _and_ has cleaner array syntax than Bash. :grin:

Anyway, yeah, basically: _always_ double-quote parameters in a shell script, unless you specifically need a particular parameter to be split in a particular situation.

As for this actual issue, I'll write up a PR to fix up the install scripts soon, once I've had a chance to test them out in a few different weird-path scenarios. 😄
