### ISSUE TITLE
BPM Settings tab doesn't get created when settings is opened from the mac title bar

### ISSUE THREAD

**Issue by Shugabuga** [ByzantineFailure/BPM-for-Discord#49]
<img width="608" alt="screen shot 2016-06-07 at 10 46 25 pm" src="https://cloud.githubusercontent.com/assets/10801851/15881157/cfc13a1e-2d01-11e6-9ff5-c9c85e77d516.png">

The settings panel disappeared after Discord did some UI changes (the same ones that removed the emote popup button). 

Using Discord PTB 1.0.0 (0.0.17) with BPM for Discord version 0.8.6 Beta.

**Comment by ByzantineFailure** [comment]
Shit, nice heads up.  ...I should _really_ be using the PTB as it's a nice canary for upcoming UI breakage.  Will look into this.

**Comment by ByzantineFailure** [comment]
Finally home, had some time to look into this.

Discord PTB 1.0.0 (0.0.17), BPM 0.8.6-beta, looks like it's there for me.  Does this issue occur for you?  It's in the nature of Discord that it might not anymore -- its desktop client is literally just loading a webpage.

**Comment by Shugabuga** [comment]
Found the issue, and it is sure odd...

![wtf-discord](https://cloud.githubusercontent.com/assets/10801851/15986010/9d713b3c-2fcb-11e6-8d49-27a9cdf308b6.gif)

There's _two_ ways into Settings. One with File -> Preferences (or `COMMAND` + `,`) and another by clicking the gear icon. I think the first method is only for Macs, though.

It's weird that it is in one place and not the other when they should be identical.

**Comment by ByzantineFailure** [comment]
Ah _hah_.  Okay, so this actually makes a lot of sense.

[The settings tab is injected via an `onclick` listener on the settings button in the UI](https://github.com/ByzantineFailure/BPM-for-Discord/blob/discord/discord/addon/settings/settings.js#L46), so if you open it via preferences up top it makes sense that the BPM tab doesn't exist.

Fixing this would require moving from a listener on the settings button to a DOM modification listener looking for the settings pane.  That's... rather a lot of work, but I'd like to have the experience be uniform between platforms.

Issue renamed, labelled properly.

**Comment by ByzantineFailure** [comment]
Plus it'll be fun to learn how MutationObservers work anyway.

**Comment by ByzantineFailure** [comment]
I have a MutationObserver-based fix up and cooking after about 15 minutes and it just worked with no problems.  This scares the shit out of me and I will be testing it before even committing it locally.

**Comment by ByzantineFailure** [comment]
I'm going to keep this bug open until release -- I don't have a mac to test this, will close on confirmation.

**Comment by Shugabuga** [comment]
I have a Mac. Do you need me to test it?

**Comment by ByzantineFailure** [comment]
That'd be pretty nice -- I assume you have the build chain for vanilla BPM set up?  The only additional things for building this are:
1.  Having webpack on your PATH (`npm install -g webpack`)
2.  Having asar on your PATH (`npm install -g asar`)

Everything should just come out in `build/discord`.

**Comment by Shugabuga** [comment]
I have the build chains for both. I'll build everything tomorrow and tell you how it goes.

**Comment by Shugabuga** [comment]
Sorry for the delay, I was busy.

I just built it and it works! Closing this...

**Comment by ByzantineFailure** [comment]
1.  Filed bug
2.  Added repro steps
3.  Tested my fix
4.  Closed the bug after confirming it works.

...

![image](https://cloud.githubusercontent.com/assets/4991977/16091185/66b7efa4-32e7-11e6-9432-ab500ae5a37e.png)

**Comment by Shugabuga** [comment]
![[](/twiwink)](https://cloud.githubusercontent.com/assets/10801851/16092831/6322aa44-3307-11e6-8bab-f4c156ae9187.png) My pleasure!
