### ISSUE TITLE
Allow for searches that use OR operators instead of exclusively implicit AND searches

### ISSUE THREAD

**Issue by TallonRain** [ByzantineFailure/BPM-for-Discord#51]
Right now, BPM searches are limited to merely combined terms. For example, `+Fluttershy +luna` will return only emotes that include Fluttershy AND luna in them. This is the only search method possible outside of searching for specific subreddits. Using searches like `sr:mylittlepony sr:shymotes` return those subreddits, but are still AND searches.

A modifier to this such as `+fluttershy, +luna` or `+fluttershy || +luna` would then read as `fluttershy OR luna` and thus return all Fluttershy and all Luna emotes, like would would appear in exclusive `+fluttershy` or exclusive `+luna` searches.

To allow AND searches, either use a comma, ie `+fluttershy, +luna` to combine separate terms or just continue to use a simple space like what's used right now.

**Comment by ByzantineFailure** [comment]
This is an issue that should be resolved on the mainline -- I _could_ resolve it here, but the benefits can and should be felt by the rest of the addon.
