### ISSUE TITLE
Text emotes not working (e.g. gravestone)

### ISSUE THREAD

**Issue by JedTheKrampus** [ByzantineFailure/BPM-for-Discord#60]
For example, writing 

```
[Syd's HDD](/gravestone)
```

will result in the text being printed unchanged in Discord. But in browser implementations of BPM, it will look like this: 

![image](https://cloud.githubusercontent.com/assets/362858/21038391/de26f952-bd9a-11e6-8e4e-9b1c29f24ff7.png)

**Comment by ByzantineFailure** [comment]
Does this function outside of reddit in browser BPM?  I've never actually tried these.

**Comment by Shugabuga** [comment]
Nope. I am guessing that it's because the out-of-BPM emote regex check.

<img width="204" alt="screen shot 2016-12-09 at 3 45 53 pm" src="https://cloud.githubusercontent.com/assets/10801851/21064015/9e51aaa2-be26-11e6-93a2-6b5d2cf7d871.png">

([relevant pastebin](http://pastebin.com/u27CDZws))

**Comment by ByzantineFailure** [comment]
@JedTheKrampus Given that this issue exists in the mainline as well, I'm going to close this issue and recommend you open up an issue there:

https://github.com/Rothera/bpm
