### ISSUE TITLE
install_linux.sh assumes curl is installed, and does not exit gracefully when not installed.

### ISSUE THREAD

**Issue by CrystalSplitter** [ByzantineFailure/BPM-for-Discord#63]
The file `install_linux.sh` should run `type curl` or `command -v curl` and check for a return status of 0 ensure that it *is* installed instead of just assuming it ran properly.

It looks like a simple fix from my side, but I can't say I'm too familiar with setup the repository has currently, and would rather not contribute a "fix" that would end up introducing new bugs.

**Comment by ByzantineFailure** [comment]
Can you look this over and see if it looks good?

https://github.com/ByzantineFailure/BPM-for-Discord/pull/64

**Comment by ByzantineFailure** [comment]
Tried to ensure all the things got redirected to the right places.  Also, what distro are you using?  I've actually never used one that doesn't come with `curl` preloaded, although I suspect Arch probably doesn't.

**Comment by ByzantineFailure** [comment]
Also, I feel kind of sheepish for assuming it existed on all installs.  I'm just so used to it being there.  Good catch.

**Comment by CrystalSplitter** [comment]
It works on my end!

Debian Stretch. I started out with the minimal install (server style install) and then built the DE up from there. I just realised today I didn't have it installed.

**Comment by ByzantineFailure** [comment]
Closed via #64
