### ISSUE TITLE
Search bar rendering

### ISSUE THREAD

**Issue by PixlRush** [ByzantineFailure/BPM-for-Discord#66]
Given that discord is rolling out a search function to all of its servers, I wanted to see how many times [](/rdwut) had been searched. When I closed the final bracket of that emote it rendered out in BPM, and then the text box's cursor got moved around. This is a small thing but it could snowball very fast.

**Comment by ByzantineFailure** [comment]
Will take a look at adding it to the banned list of replacement areas

**Comment by ByzantineFailure** [comment]
Fixed via 1e559f55cccf8eb09708fd7caf4ac9a8ddd8aab7

**Comment by ByzantineFailure** [comment]
Also this: b436d87735f28180628c08599e5180576158465a

**Comment by PixlRush** [comment]
Thank you for your fixes!
