### ISSUE TITLE
The /txt! emote

### ISSUE THREAD

**Issue by PixlRush** [ByzantineFailure/BPM-for-Discord#67]
The /txt! emote is a special emote that can change the font of text passed to it. For some reason on the first pass of emote rendering it renders out as it would usually with alt text (e.g (/rdwut"Sample Text") ). However when you edit the text it will re-render the "emote" in the font specified by a flag (e.g. (/txt!-comicsans!"bad pun") ). I have no idea why this works, or how it does, but it just does this weird thing. As another thing the alternate font flag re-rendering thing appears when you edit other emotes with the flags as well.

**Comment by ByzantineFailure** [comment]
Seems to be potentially related to:
https://github.com/Rothera/bpm/issues/38

**Comment by ByzantineFailure** [comment]
I'm going to close this issue as it's in the mainline and already there.
