### ISSUE TITLE
Issues with 8.19

### ISSUE THREAD

**Issue by RacquelSilverSpirit** [ByzantineFailure/BPM-for-Discord#68]
Installed the latest released 8.19 can see the BPM in settings menu. In BPM settings below better discord if settings are applied then restarted for them to take effect they are reset to the default again tried it two times both times the changes reset to default. so can't move the emote search box from the default place to the top right for example.

**Comment by ByzantineFailure** [comment]
Fuck.  Ugh, okay, will look into this.

**Comment by ByzantineFailure** [comment]
Super late, but resolved.
