### ISSUE TITLE
Distribute releases in .zip

### ISSUE THREAD

**Issue by Hithroc** [ByzantineFailure/BPM-for-Discord#69]
A lot of new people don't have 7zip installed, which makes installation process harder and more frustrating: you have to download 7zip and have administrator rights on the machine. Of course you can download portable 7zip and use it without installer, but that doesn't make installation process any easier.

**Comment by ByzantineFailure** [comment]
I actually wanted to do this initially, but I discovered to my rather _intense_ chagrin that MS' `.zip` tool doesn't actually support long file paths which are required when distributing a node application (which this is).

[See this comment here from December 2015](https://github.com/ByzantineFailure/BPM-for-Discord/blob/discord/Makefile#L346)

I'm going to close this but believe me when I say I'd prefer `.zip` if Windows' tooling supported it (Similarly I am unwilling to distribute this differently for different OSs when the only difference is compression format).
