### ISSUE TITLE
BPM settings don't show in upcoming full screen settings.

### ISSUE THREAD

**Issue by Jibodeah** [ByzantineFailure/BPM-for-Discord#72]
This is more an upcoming problem rather than a current one. There's an upcoming revamp of the settings screen which is already live in Canary. It looks like this:

![image](https://cloud.githubusercontent.com/assets/1408692/24917592/9398b0b4-1ed5-11e7-9e7a-b48f869d2bbf.png)

You'll note the lack of a 'BPM' section in the navbar on the left! This makes the BPM settings unreachable.

...Incidentally adding a shortcut to the BPM settings on the right click menu that appears when you right click the settings cog would make it more consistent with the other sections.

**Comment by ByzantineFailure** [comment]
Aw fuck.  Thanks for the heads up, looks like I have some work to do.

**Comment by ByzantineFailure** [comment]
@Jibodeah https://github.com/ByzantineFailure/BPM-for-Discord/pull/73

When these changes drop I'll merge and release this PR.  Thanks for the heads up.

**Comment by Jibodeah** [comment]
Good to know! ...and no problem. Guess this is what us Canary users are for anyway.

**Comment by ByzantineFailure** [comment]
Yep!  ❤️

**Comment by bb010g** [comment]
This is a bigger issue now that it's the default in stable.

**Comment by ByzantineFailure** [comment]
@bb010g merged in!
