### ISSUE TITLE
BPM is showing up in server settings

### ISSUE THREAD

**Issue by LiruMouse** [ByzantineFailure/BPM-for-Discord#74]
It doesn't belong there, right?
Normal Discord for Windows (well, technically Canary, but it probably reproduces on the mainline)

To reproduce: Create a server (or be an admin on a server) and open server settings.
![image](https://cloud.githubusercontent.com/assets/1280100/25712853/c70e143c-30c0-11e7-8cda-afb5e8c0e5d5.png)

**Comment by ByzantineFailure** [comment]
Yep.  It is 100% definitely not supposed to do that.  I'll create a server (I don't own one, didn't have the chance to test this scenario) and test out workarounds.

I'm going to probably push out the fix w/ the next update to core BPM -- this isn't a breaking issue, so I don't see much reason to push off-cycle.

**Comment by ByzantineFailure** [comment]
Holy shit.  Discord broke everything style-wise and all the classnames are now some autogenerated gobbledygook from their CSS compiler.  This also broke the fuck out of settings.  Again.

Goddamn.  Okay, well, fuck this, I'm doing it later.

**Comment by ByzantineFailure** [comment]
Fixed by way of this being broken.  I'm planning on permanently moving the settings panel, so I'll close this ticket.
