### ISSUE TITLE
add ability to add other subreddits to the list emotes are pulled from (like core BPM)

### ISSUE THREAD

**Issue by jamesmanning** [ByzantineFailure/BPM-for-Discord#75]
@ByzantineFailure I think this is different than #19 but if I'm wrong, please close as a duplicate. 😄 

In the BPM settings it's listed as 'Custom Subreddits' but I wasn't sure if the BPM for Discord would need to treat user-added subreddits any different than the default list, so hoping this is possible.  Is BPM for Discord more restricted than the BPM extension because it runs in a frame?

![image](https://cloud.githubusercontent.com/assets/225626/25777319/015cd2a2-32a8-11e7-94d1-0abd16fada6c.png)

**Comment by ByzantineFailure** [comment]
This is unfortunately not possible because reddit is pretty picky about where it will allow its stylesheets to be loaded from.  BPM's core emotes get around this by just building custom stylesheets for its own use, but pulling subreddits will not be possible on Discord.  Sorry :(

**Comment by jamesmanning** [comment]
@ByzantineFailure is there any other option for importing 'external' emotes?  i've already got those other emotes in a json file, so if there's either a place i could write a file (whatever structure you preferred) or some other way of getting them in, that'd be great.  It certainly doesn't need to be scraping random subreddits, I can completely understand that being problematic. 😄

**Comment by ByzantineFailure** [comment]
The only thing I can think of is the custom JS support that is there.  You can write JS files which will be executed in the browser context:

https://github.com/ByzantineFailure/BPM-for-Discord/blob/discord-v0.9.1-beta/discord/CUSTOMJS.md

You would need to distribute the file you create to the others who would use it, but it's doable -- just create a file that loads some CSS as a static string and throws it on the page as a `<style>` tag.

It's not great but in the absence of the ability to retrieve CSS from reddit it's what I've got.
