### ISSUE TITLE
Does not convert html-ised markdown emotes in custom embeds

### ISSUE THREAD

**Issue by Jibodeah** [ByzantineFailure/BPM-for-Discord#76]
So I admit this is a bit of a odd use case but in rich embeds (the type only creatable by bots) the markdown `[link](format)` actually works. So you can have a emote code in it and, sure enough, it's invisible to those without BPM.

Trouble is, it's also invisible to those *with* BPM. See images below...

![Rich embed, with no emote visible](https://user-images.githubusercontent.com/1408692/27199286-561768a0-520d-11e7-957e-3c01fa972aba.png)

![The html source of the embed, with the invisible link that the emote code produces visible](https://user-images.githubusercontent.com/1408692/27199316-7a081b9c-520d-11e7-88f5-d9da4af96c25.png)

In theory it shouldn't be too hard to find and convert these emotes. ...It's what BPM itself does on reddit. It should probably only be done in the 'description' section of embeds too.

(...oh and while I probably could workaround this by escaping the emotes so they get rendered as their codes, that seems kinda messy)

**Comment by ByzantineFailure** [comment]
Hm.  that's... _quite_ niche.  Nice, well-formed bug report, btw.

What's going on here seems to be that there's some conflict between the way things are parsed and handled outside reddit and inside reddit.  Unsure what's up, will have to investigate.

**Comment by ByzantineFailure** [comment]
Can you link me to an example post I can use to play around?

**Comment by ByzantineFailure** [comment]
Reference emote please ignore

``[](/ajwut)``

**Comment by ByzantineFailure** [comment]
Changes made and successful.  Will go out with the next update of BPM's core.
