### ISSUE TITLE
Discord update broke one-click insertion of emotes

### ISSUE THREAD

**Issue by Pazns** [ByzantineFailure/BPM-for-Discord#80]
Since a recent Discord update (2017-07-20, I think ?), the way BPM gets the input textarea is broken and doesn't work at all.

Just by looking at `bpm.js` release file, I see that the old way with `getElementsByClassName('channel-textarea-inner');` can't work since the identifier `channel-textarea-inner` doesn't exist anymore.

I silly-tested things and found that searching `channel-text-area-default` makes it to work again.
This is the first textarea–parent class identifier that isn't some generated bullshit like `channelTextArea-1HTP3C`.

Note that the automatic insertion is still somehow broken.
User must type something in the field for it to be able to send the emote auto-inserted.
There is probably an event triggering after user real input that BPM doesn't trigger by programmatically inserting text.

**Comment by ByzantineFailure** [comment]
Gah, okay.  Looks like I need to find some time in the coming week to sit
down and hammer out a few of these bugs.

**Comment by ByzantineFailure** [comment]
Nevermind, you seem to have created a PR.  Taking a glance over it.

**Comment by ByzantineFailure** [comment]
Resolved via #82
