### ISSUE TITLE
No BPM entry in Discord settings panel.

### ISSUE THREAD

**Issue by Pazns** [ByzantineFailure/BPM-for-Discord#83]
I can't find the BPM entry in the settings screen.

Therefore, I'm unable to tweak BPM.

**Comment by Tadaboody** [comment]
On the other hand, [this issue is fixed now](https://github.com/ByzantineFailure/BPM-for-Discord/issues/74)

**Comment by Pazns** [comment]
Always look on the bright side of life !

**Comment by ByzantineFailure** [comment]
I'm looking into just moving everything to the "Settings" link in the search window.  Much less fickle to maintain that way.  That's not a small feature, though.

**Comment by ByzantineFailure** [comment]
@Pazns https://g.co/kgs/onh2Cp

**Comment by ByzantineFailure** [comment]
Resolved in most recent release by moving to search window:

![image](https://user-images.githubusercontent.com/4991977/28504317-e4c8896a-6fc9-11e7-94bb-2792f39fc4ac.png)

Closing this issue.
