### ISSUE TITLE
Insertion from search box fails without subsequent text entry.

### ISSUE THREAD

**Issue by alamais-df** [ByzantineFailure/BPM-for-Discord#91]
Clicking on an emote in the search box will appear to insert the emote text, but the text box behaves as if nothing happened.  If there was already text, hitting Return will send that text without the emote added; if it was empty, Return does nothing, again as if no text was added and so the box is still empty.  Typing any additional text afterwards (even just a space) will make it recognize that the emote text was added.

This is on Mac (two different ones, El Cap and Mavericks), with the BetterDiscord version, latest BPM (v0.10.0).

**Comment by ByzantineFailure** [comment]
Fixed as part of #92
