### ISSUE TITLE
Clicking on an emote in the search box does not insert emote text

### ISSUE THREAD

**Issue by thejbw** [ByzantineFailure/BPM-for-Discord#94]
Nothing seems to happen when clicking the emote in the search box.

BPM for betterdiscord version, BD and BPM up to date as of 11/11/17

**Comment by CrystalSplitter** [comment]
This has been happening for about 2 weeks for me. Have tested on Debian and Windows 10 with the latest version of Discord (9th of November, 2017), and the latest version of BPM (66.261), and it *should* be the lastest version of BPM-for-Discord.

It could be something wrong with the install process, as I do know of users who do *not* have the error. Reinstalling Discord/BPM-for-Discord however has not solved the problem yet (through batch or shell script).

**Comment by Shugabuga** [comment]
By any chance is this happening while in the inbox?

**Comment by ByzantineFailure** [comment]
Query selector updated, should be fixed in the next update.  Checking with Typhos if there's a BPM core update inbound before pushing this out.
